language: python

python:
  - '3.9'

branches:
  only:
    - develop

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py collectstatic --noinput  -i node_modules -i vendor -i scss -i scripts

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="app.settings"

script:
  - python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: $API_KEY
    app: $APP_NAME
    on:
      branch: main
