language: python
python:
  - '3.9'

# safelist
branches:
  only:
    - develop

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

# command to install dependencies
before_script:
  - python manage.py collectstatic

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="app.settings"

# command to run tests
script:
  - python manage.py test
