# Generated by Django 3.2.9 on 2022-01-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=10, unique=True),
        ),
    ]
