# Generated by Django 3.2.9 on 2022-01-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_cabinet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestassociate',
            old_name='cabinet_id',
            new_name='cabinet',
        ),
        migrations.RenameField(
            model_name='requestassociate',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='requestassociate',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
