# Generated by Django 3.2.9 on 2022-01-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_auto_20220107_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestassociate',
            name='cabinet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestassociate',
            name='receiver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestassociate',
            name='sender_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
