# Generated by Django 3.2.9 on 2022-01-04 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('care_address', models.CharField(max_length=400)),
                ('cares', models.CharField(max_length=100)),
                ('care_price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('group_id', models.CharField(default='m#oxh2l*4%^67jr0rvey%ev=yr7vxt$ycyne02k$2@w6kroe(e', max_length=400)),
                ('total_visit_per_day', models.IntegerField(default=1)),
                ('delta_visit_per_day', models.IntegerField(default=1)),
                ('delta_visit_per_hour', models.IntegerField(blank=True, null=True)),
                ('number_of_days', models.IntegerField(blank=True, null=True)),
                ('day_per_week', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
