# Generated by Django 3.2.9 on 2021-12-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('care_address', models.CharField(max_length=400)),
                ('cares', models.CharField(max_length=100)),
                ('care_price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('group_id', models.CharField(default='g1*aph+r#ujs)uwbtrgl73x)!fj4r&r73@_&&vtgmv#3^uxkm!', max_length=400)),
                ('total_visit_per_day', models.IntegerField()),
                ('delta_visit_per_day', models.IntegerField(default=1)),
                ('delta_visit_per_hour', models.IntegerField(default=0)),
                ('number_of_days', models.IntegerField()),
                ('day_per_week', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
