# Generated by Django 3.2.9 on 2021-12-19 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nursapps.agenda.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('care_address', models.CharField(max_length=400)),
                ('cares', models.CharField(max_length=100)),
                ('care_price', models.CharField(max_length=20)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('group_id', models.CharField(default=nursapps.agenda.models.random_group_id, max_length=400)),
                ('total_visit_per_day', models.CharField(max_length=2)),
                ('delta_visit_per_day', models.CharField(default=1, max_length=2)),
                ('delta_visit_per_hour', models.CharField(max_length=2)),
                ('days_number', models.CharField(max_length=2)),
                ('day_per_week', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
