# Generated by Django 3.2.9 on 2022-01-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group_id',
            field=models.CharField(default='=2%+@p14s*m876n$p7_j4%ta_-klfapu6pdmg!geut#5)5n3#t', max_length=400),
        ),
    ]
