# Generated by Django 3.2.9 on 2021-12-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='days_number',
            new_name='nb_visit_per_days',
        ),
    ]
