# Generated by Django 3.2.9 on 2022-01-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20220105_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='group',
            new_name='events',
        ),
    ]
