# Generated by Django 3.2.9 on 2022-01-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_rename_group_event_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.events'),
        ),
    ]
