# Generated by Django 3.2.9 on 2021-12-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_rename_nb_visit_per_days_event_days_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='choice_event_edit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
