# Generated by Django 3.2.9 on 2021-12-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_event_choice_event_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='choice_event_edit',
        ),
    ]
