# Generated by Django 3.2.9 on 2021-12-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_remove_event_choice_event_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='days_number',
            new_name='number_of_days',
        ),
    ]
