# Generated by Django 3.2.9 on 2021-12-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_rename_days_number_event_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='care_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_per_week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='delta_visit_per_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='delta_visit_per_hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_visit_per_day',
            field=models.IntegerField(),
        ),
    ]
