# Generated by Django 3.2.9 on 2021-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_auto_20211230_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='delta_visit_per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
