# Generated by Django 3.2.9 on 2021-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_alter_event_delta_visit_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='care_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
