# Generated by Django 3.2.9 on 2021-12-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_alter_event_care_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
