# Generated by Django 3.2.9 on 2021-12-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_alter_event_day_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='delta_visit_per_hour',
            field=models.IntegerField(default=0),
        ),
    ]
